import type { Metadata } from "next";
import { notoSansJP, montserrat } from "./fonts";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { AccessibilityProvider } from "@/components/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${notoSansJP.variable} ${montserrat.variable}`}
      suppressHydrationWarning
    >
      <body className={`${notoSansJP.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AccessibilityProvider>{children}</AccessibilityProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
